import argparse
import json
from pathlib import Path


def load_record(record_file: Path) -> dict:
    if not record_file.exists():
        return {}
    with open(record_file, "r", encoding="utf-8") as f:
        return json.load(f)


def safe_unlink(path: Path) -> bool:
    if path.exists() and path.is_file():
        path.unlink()
        return True
    return False


def main() -> int:
    parser = argparse.ArgumentParser(description="Delete synced files listed in sync record.")
    parser.add_argument(
        "--record-file",
        default="videos/.sync_last.json",
        help="Record file generated by sync_sora_daily_videos.py",
    )
    parser.add_argument("--keep-record", action="store_true", help="Do not delete record file after cleanup.")
    args = parser.parse_args()

    record_file = Path(args.record_file).resolve()
    data = load_record(record_file)
    if not data:
        print(f"No record found: {record_file}")
        return 0

    deleted = 0
    for item in data.get("synced_files", []):
        mp4 = item.get("mp4")
        txt = item.get("txt")
        thumbnail = item.get("thumbnail_file")
        if mp4 and safe_unlink(Path(mp4)):
            deleted += 1
            print(f"deleted: {mp4}")
        if txt and safe_unlink(Path(txt)):
            deleted += 1
            print(f"deleted: {txt}")
        if thumbnail and safe_unlink(Path(thumbnail)):
            deleted += 1
            print(f"deleted: {thumbnail}")

    if not args.keep_record and record_file.exists():
        record_file.unlink()
        print(f"deleted record: {record_file}")

    print(f"cleanup done. files deleted: {deleted}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
