import argparse
import asyncio
import json
from pathlib import Path

from conf import BASE_DIR
from uploader.douyin_uploader.main import DouYinVideo, douyin_setup
from utils.files_times import generate_schedule_time_next_day, get_title_and_hashtags


def load_synced_entries(record_file: Path) -> list[dict]:
    if not record_file.exists():
        return []
    with open(record_file, "r", encoding="utf-8") as f:
        data = json.load(f)
    entries: list[dict] = []
    for item in data.get("synced_files", []):
        mp4 = item.get("mp4")
        if mp4:
            video_path = Path(mp4)
            if not video_path.exists():
                continue

            thumb = item.get("thumbnail_file")
            thumb_path = Path(thumb) if thumb else None
            if thumb_path and not thumb_path.exists():
                thumb_path = None

            # Backward-compatible fallbacks.
            if thumb_path is None:
                for cand in (video_path.with_suffix(".cover.jpg"), video_path.with_suffix(".png")):
                    if cand.exists():
                        thumb_path = cand
                        break

            entries.append({"video": video_path, "thumbnail": thumb_path})
    return entries


def parse_daily_times(value: str) -> list[int]:
    result = []
    for part in value.split(","):
        part = part.strip()
        if not part:
            continue
        hour = int(part)
        if hour < 0 or hour > 23:
            raise ValueError(f"Invalid hour: {hour}")
        result.append(hour)
    if not result:
        result = [15]
    return result


async def upload_files(entries: list[dict], daily_times: list[int]) -> int:
    account_file = Path(BASE_DIR) / "cookies" / "douyin_uploader" / "account.json"
    publish_datetimes = generate_schedule_time_next_day(len(entries), 1, daily_times=daily_times)

    ok = await douyin_setup(account_file, handle=False)
    if not ok:
        raise RuntimeError("Douyin cookie is invalid. Please re-login to refresh cookies.")

    for index, entry in enumerate(entries):
        file = entry["video"]
        thumbnail_path = entry.get("thumbnail")
        title, tags = get_title_and_hashtags(str(file))

        print(f"uploading: {file}")
        print(f"title: {title}")
        print(f"tags: {tags}")

        if isinstance(thumbnail_path, Path) and thumbnail_path.exists():
            app = DouYinVideo(title, file, tags, publish_datetimes[index], account_file, thumbnail_path=thumbnail_path)
        else:
            app = DouYinVideo(title, file, tags, publish_datetimes[index], account_file)
        await app.main()
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Upload files listed in sync record to Douyin.")
    parser.add_argument(
        "--record-file",
        default="videos/.sync_last.json",
        help="Record file generated by sync_sora_daily_videos.py",
    )
    parser.add_argument(
        "--daily-times",
        default="15",
        help="Comma-separated publish hours, e.g. 15 or 10,15,20",
    )
    args = parser.parse_args()

    record_file = Path(args.record_file).resolve()
    entries = load_synced_entries(record_file)
    if not entries:
        print(f"No synced files found in record: {record_file}")
        return 2

    daily_times = parse_daily_times(args.daily_times)
    try:
        asyncio.run(upload_files(entries, daily_times), debug=False)
    except Exception as e:
        print(f"Upload error: {e}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
